### PR TITLE
Fixes #1501

### LINKED ISSUE #1501: CircleCI doesn't pass for any branches other than master
The `oae-version` test fails all the time if we're testing some branch other than master, because of this line:

```
- run: git submodule foreach -q --recursive 'branch="$(git config -f $toplevel/.gitmodules submodule.$name.branch)"; [ -z "$branch" ] && git checkout master || git checkout $branch'
```

Which means that we have to change the `oae-version` so that it expects `3akai-ux` to be a submodule and not a branch.

### PR DESCRIPTION
**Pull request by brecke**
Removed unnecessary line from CCI config
Slight change in test
Refactored a bit

Hopefully CCI will pass tests starting now ^_^

### CODE REVIEW

File: node_modules/oae-version/lib/api.js [hunk 1]
```diff
@@ -79,20 +80,48 @@ var getVersion = module.exports.getVersion = function(callback) {
...
-    _getVersionInfo(_uiPath, callback);
+
+    let submodulePointer = "";
+    let lastCheckedOutCommit = "";
+
+    gift.init(hilaryDirectory, (err, repo)  => {
+        repo.tree().contents((err, children) => {
+
+            // find the 3akai-ux submodule within the tree
+            const submodulePointer = _.find(children, (eachChild) => {
```
Comment (sallakarppinen) [inline node_modules/oae-version/lib/api.js]: You checked that this still works when 3akai is *not* a submodule? (For example when installing from package?)

Comment (brecke) [reply node_modules/oae-version/lib/api.js]: It won't work in any other situation other than the git submodule, because we're creating a reference CI/CD procedure which uses git-based installs. If the need for package installs arise in the future, we might have to re-think this approach, but hopefully that won't be necessary. Merging because all checks passed 🍾
